---
title: "Appendix"
output: html_document
---

##Function crunBMLGrid
```{r,eval=FALSE}
crunBMLGrid =
  #
  #This function call c function in R to move cars
  #grid: matrix display the grid with class "BMLGrid"
  #numStep: number of steps 
  #
  function(grid, numStep){
    
    if(any(!is.numeric(numStep)) | length(numStep) != 1 )  
      stop("numSteps need to be an positive integer")
    
    if(numStep <= 0 | numStep %% 1 != 0 )
      stop("numSteps need to be an positive integer")
    
    if(!"BMLGrid" %in% class(grid))
      stop("car need to be a BMLGrid object")
    
    grid.vec = as.vector(grid)
    row = nrow(grid)
    col = nrow(grid)
    
    newgrid = .C("runBMLGrid", matrix = as.integer(grid.vec), row = as.integer(row),
       col = as.integer(col), numStep = as.integer(numStep))$matrix
    newgrid = matrix(newgrid,nrow = row)
    class(newgrid) = c("BMLGrid",class(newgrid))
    newgrid
  }
```

##Old version(Same content with assignment2)
```{r,eval=FALSE}
creatBMLGrid=
  #
  #This function is a liitle bit different from previous ones. We use 3 to denote red car 
  #instead of 2.
  #
  function(r = 100, c = 99, ncars = c(blue = 100, red = 100), p = 0)
  {
    if(p != 0){
      blue = red = ceiling(r*c*p/2)
      ncars = c(blue, red)
    }
    if (p<0|p>0.9) stop("Density should be positive and not greater than 0.9")
    r = ceiling(r)
    c = ceiling(c)
    if(c<=0|r<=0) stop("Dimensions should be positive")
    
    
    grid = matrix(0,r,c)
    pos = sample(r*c, sum(ncars))
    
    grid[pos] = sample(rep(c(1,3),times = ncars))
    class(grid) = c("BMLGrid",class(grid))
    grid
  }



moveCar.c = 
  # 
  #This function is used to move car.
  #In this function, we create a new matrix based on the original one. This new matrix        
  #has all elements in the matrix moved upwards(rightwards). Thus, by finding the 
  #difference between the two matrix, we can easily find which cars can move. When
  #it's time to move the blue cars, we move downwards the orignal grid(matrix) to get   
  #the new one and calculate a difference matrix. The locations in that matrix which 
  #hasvalue -1 are the locations we should move the car. For red cars, we need to move 
  #leftwards the grid and find locations which have value -3 in difference matrix. And 
  #these are the locations we should move the car. 
  #time implies which type of car we need to move.
  # 
  #
function(grid,time){
  if(time%%2 == 1){
    num.row = nrow(grid)
    grid.new = rbind(grid[num.row,], grid[1:(num.row)-1),])
    
    findMov = which(grid.new - grid == -1 ) #this is the index of blue cars which can move
    grid[findMov] = 0
    
    rule = (findMov - 1L)%%nrow(grid) #rule to judge whether the cars get to the edge
    findMov[rule==0] =  
      findMov[rule==0] + nrow(grid) - 1 
    findMov[rule != 0] = 
      findMov[rule != 0] - 1
    
    grid[findMov] = 1
  }
  else{
    grid.new = cbind(grid[,2:ncol(grid)],grid[,1])
    
    findMov = which(grid.new - grid == -3 )#this is the index of red cars which can move
    grid[findMov] = 0
    
    rule = findMov - (ncol(grid)-1)*nrow(grid) #rule to judge whether the cars get to the edge
    findMov[rule>0] =  
      findMov[rule>0] - (ncol(grid)-1)*nrow(grid)
    findMov[rule <= 0] = 
      findMov[rule <= 0] + nrow(grid)
    
    grid[findMov] = 3
  }
  grid
}

runBMLGrid = 
  #
  #move car numSteps times
  #
  function(grid, numSteps){
    for(i in 1:numSteps)
      grid = moveCar.c(grid,i)
    grid
  }


carVelocity = 
  function(grid,carType){
    if(carType == 1){
      grid.new = rbind(grid[nrow(grid),], grid[1:(nrow(grid)-1),])
      blueMov = length(which(grid.new - grid == -1 ))
      velocity = blueMov/length(which(grid==1))
    }
    else {
      grid.new = cbind(grid[,2:ncol(grid)],grid[,1])
      redMov = length(which(grid.new - grid == -3 ))
      velocity = redMov/length(which(grid==3))
    }
    velocity
  }

summary.BMLGrid = 
  #
  #how many cars(red?blue?)
  #how many cars are blocked
  function(grid){
    r = nrow(grid)
    c = ncol(grid)
    
    car.num = length(which(grid != 0))
    blue.num = length(which(grid == 1))
    red.num = length(which(grid == 3))
    
    notmovBlue = blue.num - velocityBlue*blue.num
    notmovRed = red.num - velocityBlue*red.num 
    
    velocityBlue = round(carVelocity(grid, 1), 3)
    velocityRed = round(carVelocity(grid, 3), 3)
    
    cat(' This is a ',r,'*',c,'GRID:',
        '\n','There are total',car.num,'CARS:',
        '\n','                  BLUE               RED             ',
        '\n','NUM           ',blue.num,'               ',red.num,
        '\n','BLOCKED NUM   ',notmovBlue,'                ',notmovRed,
        '\n','VELOCITY      ',velocityBlue,'              ',velocityRed,'\n')
  }

plot.BMLGrid = 
  
  function(grid, main){
    image(t(grid[nrow(grid):1,]),col=c("white","blue","red"),main = main)
    box()
  }
```

##Code to analyse
```{r,eval=FALSE}
if(!exists("dataDir"))
  dataDir = "e://2015 spring/242/assignment4/BMLGrid/BMLGrid/"
if(!exists("dataDir1"))
  dataDir1 = "e://2015 spring/242/assignment4/"

setwd(dataDir)
dyn.load("BML.dll")
setwd(dataDir1)
source("Cbml.R")
source("Rbml.r")

#This part is to compare R version and C version which both have similar algorithm.

time1 = integer(30)
time2 = integer(30)

grid = creatBMLGrid(100,100,p = 0.3)

temp = grid
for(i in 1:30){
  time1[i] = system.time({temp = runBMLGrid(grid,40*i)})[1]
}

temp = grid
for(i in 1:30){
  time2[i] = system.time({temp = crunBMLGrid(grid,40*i)})[1]
}

plot(time1,xlim = c(0,32),ylim = c(0,1.5),type = 'l',xlab = 'STEPS/40',ylab = 'TIME/sec',
     main = 'Comparing for 2 approaches')
lines(time2,col = 'red')
legend("topleft",legend = c('Approach 1','Approach 2'),
       col=c("black","red"),lty =1)

#This part considers about how density will influence the time consuming.

time3 = integer(100)
k = 1
density = seq(0.2,0.8,length = 100)
for(i in density){
  grid3 = creatBMLGrid(1000,1000,p = i)
  time3[k] = system.time(crunBMLGrid(grid3,100))[1]
  k=k+1
}

plot(density, time3, main = "TIME VS DENSITY(grid:1000*1000,numStep:100)", 
     xlab = "DENSITY",ylab = "TIME/sec")
lines(lowess(time3~density),col = "red")


#This part considers about how number of steps will influence the time consuming
time4 = integer(19)
grid4 = creatBMLGrid(1000,1000,p=0.4)
numStep = seq(1000,10000,500)
for(i in numStep){
  time4[i/500-1] = system.time(crunBMLGrid(grid4,i))[1]
}
plot(numStep, time4, main = "TIME VS NUMBER of STEPS(grid:1000*1000,DENSITY:0.4)", 
     xlab = "NUMBER of STEPS",ylab = "TIME/sec")
lines(lowess(time4~numStep), col = "red")
#This part considers about how size of grid will influence the time consuming
time5 = integer(20)
for(i in 1:20){
  grid5 = creatBMLGrid(i*50,i*50,p=0.4)
  time5[i] = system.time(crunBMLGrid(grid5,500))[1]
}
size = (50*(1:20))^2
plot(size, time5, main = "TIME VS SIZE(NUMSTEP:500,DENSITY:0.4)", 
     xlab = "SIZE",ylab = "TIME/sec")
lines(lowess(time5~size),col = "red")

```